### ISSUE TITLE
Sending partitionId in setMessages

### ISSUE THREAD

**Issue by pushpesh4u** [nmred/kafka-php#14]
The Produce::setMessages call requires a partitionId to be sent to which the message will be sent.

Shouldn't this be decided by the zookeeper rather than the producer to specify it.

Is there a way to list all partitions in a given topic.

Can we create topics/partitions.

**Comment by Timandes** [comment]
By having a notion of parallelism—the partition—within the topics, Kafka is able to provide both ordering guarantees and load balancing over a pool of consumer processes. This is achieved by assigning the partitions in the topic to the consumers in the consumer group so that each partition is consumed by exactly one consumer in the group. By doing this we ensure that the consumer is the only reader of that partition and consumes the data in order. Since there are many partitions this still balances the load over many consumer instances. Note however that there cannot be more consumer instances than partitions.

---- http://kafka.apache.org/documentation.html#introduction

**Comment by pushpesh4u** [comment]
Ok, is there a way to get all available partitions for a given topic. As of now, we are sending the messages to partitionid - 0.

**Comment by Timandes** [comment]
Use @andreiz's php-zookeeper:

    get /brokers/topics/test
    {"version":1,"partitions":{"0":[0]}}

**Comment by pushpesh4u** [comment]
I can do that, but the zookeeper's object is kept private when being initialised in `Produce::__construct`.

```
private $client;
...
...
...
   private function __construct($hostList, $timeout = null) {
        $zookeeper = new \Kafka\ZooKeeper($hostList, $timeout);
        $this->client = new \Kafka\Client($zookeeper);
  }

```
Creating another object would be overhead.

**Comment by Timandes** [comment]
Ha, interesting.

See also: #13.

May be we could add new method `getAvailablePartitions()`. @nmred

**Comment by nmred** [comment]
Add method `Produce::getAvailablePartitions($topicName)` use get all available partition

Add method `getClient()` get `Kafka\Client` object, also use this object method `getTopicDetail()` get partition
