### ISSUE TITLE
Unwritable Stream in Producer

### ISSUE THREAD

**Issue by jebentier** [nmred/kafka-php#20]
I'm executing a long running producer job that is taking data from a database and putting it onto a Kafka topic for later processing.  Sporadically, this producer job will error out with the exception `Could not write 16353587 bytes to stream`.  I've looked into the code and tracked it down to the `Kafka\Socket` object's `write($buf)` function here:
```php
$writable = stream_select($null, $write, $null, $this->sendTimeoutSec, $this->sendTimeoutUsec);
if ($writable > 0) { ... }
if (false !== $writable) { ... }
throw new \Kafka\Exception\Socket('Could not write ' . strlen($buf) . ' bytes to stream');
```

The only information I can find about this is that it has something to do with the stream no longer responding, or responding with an error.  No errors are thrown to the system logs so this is becoming more and more difficult to debug.  Any help would be appreciated.

**Comment by davidsheldon** [comment]
I suspect it's timing out on the write - maybe your OS buffer is full. 

Try increasing the timeouts, e.g. `$producer->setStreamOptions(['RecvTimeoutSec' => 10, 'SendTimeoutSec' => 10]);`

**Comment by Crim** [comment]
Yeah this is the issue I ran into which made me submit the PR to expose those socket/stream options.  Adjusting those helped mitigate it to some degree for me....  what helped more was retrying the write a few times before giving up.  Typically on the first retry it would succeed.  I don't fully understand why this would work where just adjusting the socket timeout to 2x the previous value didn't.

Here's the code I have in a local repository to do the retry logic.
https://github.com/nmred/kafka-php/compare/master...Crim:selectRetry

I never made a PR because it seems like a hacky fix, and I'd love to understand better whats going on / get input from you guys

**Comment by nmred** [comment]
Fixed!
